packages:
  - .
  - apps/*

ignoredBuiltDependencies:
  - isolated-vm
  - msgpackr-extract

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - argon2
  - prisma
  - sharp
  - unrs-resolver
