use crate::auth_context::TenantContext;
use crate::error::DataError;
use base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD};
use futures::future::BoxFuture;
use sea_orm::{
    ConnectionTrait, DatabaseConnection, DatabaseTransaction, DbBackend, DbErr, Statement,
    TransactionTrait,
};
use tracing::{error, warn};

// Sealed Internal Wrapper
pub struct RawConnection {
    pub(crate) txn: DatabaseTransaction,
}

impl RawConnection {
    pub(crate) fn new(txn: DatabaseTransaction) -> Self {
        Self { txn }
    }
}

/// A wrapper around a database transaction that is guaranteed to be scoped to a specific tenant.
pub struct TenantScoped<C> {
    pub(crate) inner: C,
    pub(crate) tenant_id: crate::auth_context::TenantId,
    pub(crate) user_id: Option<crate::auth_context::UserId>,
}

impl<C> TenantScoped<C> {
    pub(super) fn new(
        inner: C,
        tenant_id: crate::auth_context::TenantId,
        user_id: Option<crate::auth_context::UserId>,
    ) -> Self {
        Self {
            inner,
            tenant_id,
            user_id,
        }
    }
}

impl TenantScoped<RawConnection> {
    pub(crate) fn txn(&self) -> &DatabaseTransaction {
        &self.inner.txn
    }

    pub(crate) async fn commit(self) -> Result<(), DbErr> {
        self.inner.txn.commit().await
    }

    pub(crate) async fn rollback(self) -> Result<(), DbErr> {
        self.inner.txn.rollback().await
    }
}

// Implement Sealed trait for TenantScoped
impl super::repository::private::Sealed for TenantScoped<RawConnection> {}

// TenantRepository implementation is in repository.rs

/// Executes a closure within a tenant-scoped transaction.
///
/// **Note:** This function relies on the `flexi.authorize_tenant` PL/pgSQL function.
/// The `token` must be a valid signed v2 token generated by `KeyManager`.
pub async fn with_tenant_tx<F, R>(
    pool: &DatabaseConnection,
    ctx: &TenantContext,
    token: &str,
    f: F,
) -> Result<R, DataError>
where
    F: for<'c> FnOnce(&'c TenantScoped<RawConnection>) -> BoxFuture<'c, Result<R, DataError>>
        + Send,
    R: Send,
{
    let txn = pool.begin().await.map_err(DataError::DbError)?;

    // 1. Authorize
    if let Err(e) = txn
        .execute(Statement::from_sql_and_values(
            DbBackend::Postgres,
            "SELECT flexi.authorize_tenant($1)",
            [token.into()],
        ))
        .await
    {
        // Log a sanitized message only; do not interpolate the raw DB error
        // to avoid leaking token KID or other sensitive fields into log sinks.
        warn!("Tenant authorization failed");

        let error_msg = e.to_string();
        let safe_error = [
            "Nonce already used",
            "Internal HMAC secret not set",
            "Invalid signature",
            "Token timestamp expired or future (skew > 30s)",
            "Missing or empty tenant token",
            "Invalid token format",
        ]
        .iter()
        .find(|&&m| error_msg.contains(m))
        .map(|&m| m.to_string())
        .unwrap_or_else(|| "tenant authorization failed".to_string());

        if let Err(rollback_err) = txn.rollback().await {
            error!("rollback failed after authorization failure: {rollback_err}");
        }
        return Err(DataError::TenantAuthorizationFailed(safe_error));
    }

    let token_tenant = if let Some(tid) = parse_tenant_from_token(token) {
        tid
    } else {
        if let Err(rollback_err) = txn.rollback().await {
            error!("rollback failed after token parse failure: {rollback_err}");
        }
        return Err(DataError::TenantAuthorizationFailed(
            "invalid tenant token format".to_string(),
        ));
    };
    if token_tenant != ctx.tenant_id().as_str() {
        warn!(
            expected_tenant = %ctx.tenant_id(),
            token_tenant = %token_tenant,
            "tenant mismatch between context and token"
        );
        if let Err(rollback_err) = txn.rollback().await {
            error!("rollback failed after tenant mismatch: {rollback_err}");
        }
        return Err(DataError::TenantAuthorizationFailed(
            "tenant mismatch between context and token".to_string(),
        ));
    }

    let scoped = TenantScoped::new(
        RawConnection::new(txn),
        ctx.tenant_id().clone(),
        ctx.user_id().cloned(),
    );

    match f(&scoped).await {
        Ok(result) => match scoped.commit().await {
            Ok(()) => Ok(result),
            Err(commit_err) => {
                error!(
                    tenant_id = %ctx.tenant_id(),
                    "commit failed (outcome unknown): {commit_err}"
                );
                Err(DataError::CommitUnknown(commit_err.to_string()))
            }
        },
        Err(e) => {
            if let Err(rollback_err) = scoped.rollback().await {
                error!("rollback failed: {rollback_err}");
            }
            warn!(tenant_id = %ctx.tenant_id(), "tx rolled back: {e}");
            Err(e)
        }
    }
}

fn parse_tenant_from_token(token: &str) -> Option<String> {
    if token.starts_with("v4.public.") {
        let parts: Vec<&str> = token.split('.').collect();
        // v4.public.payload.footer -> expects 4 parts
        if parts.len() < 3 {
            error!("Token parts len: {}", parts.len());
            return None;
        }
        let payload_b64 = parts[2];
        let payload_and_sig_bytes = match URL_SAFE_NO_PAD.decode(payload_b64) {
            Ok(b) => b,
            Err(e) => {
                error!("Base64 decode failed for payload (len={}): {}", payload_b64.len(), e);
                return None;
            }
        };

        // PASETO v4.public payload includes the signature (64 bytes) at the end: m || sig
        if payload_and_sig_bytes.len() < 64 {
            error!("Payload too short for signature (len={})", payload_and_sig_bytes.len());
            return None;
        }
        let payload_len = payload_and_sig_bytes.len() - 64;
        let payload_bytes = &payload_and_sig_bytes[..payload_len];

        let payload_str = match std::str::from_utf8(payload_bytes) {
            Ok(s) => s,
            Err(e) => {
                error!("UTF8 decode failed: {}", e);
                return None;
            }
        };
        let json: serde_json::Value = match serde_json::from_str(payload_str) {
            Ok(j) => j,
            Err(e) => {
                error!("JSON parse failed (len={}): {}", payload_str.len(), e);
                return None;
            }
        };
        let tid = json
            .get("tenant_id")
            .and_then(|v| v.as_str())
            .map(|s| s.to_string());
        if tid.is_none() {
             error!("tenant_id missing in token payload");
        }
        return tid;
    }

    #[cfg(feature = "test-utils")]
    if let Some(tenant_id) = token.strip_prefix("dev-token:") {
        // Special dev token for tests/debug with tenant ID
        return Some(tenant_id.to_string());
    }

    #[cfg(not(feature = "test-utils"))]
    if token.starts_with("dev-token:") {
        warn!(
            "dev-token encountered in non-test build; parsing via v2 parser (tenant_id extraction bypassed)"
        );
    }

    let mut parts = token.split(':');
    let ver = parts.next()?;
    let _kid = parts.next()?;
    let _ts = parts.next()?;
    let _nonce = parts.next()?;
    let tenant_id = parts.next()?;
    let _sig = parts.next()?;
    if ver != "v2" || parts.next().is_some() {
        return None;
    }
    Some(tenant_id.to_string())
}

// Legacy exports retained for binary compatibility during migration.
// These shims now fail loudly so callers are forced to migrate.
#[deprecated(note = "Legacy migration shim; removed - use token-based authorization API")]
pub fn init_hmac_secret() -> Result<(), String> {
    Err(String::from(
        "init_hmac_secret is removed/deprecated: use token-based authorization API",
    ))
}

#[cfg(feature = "test-utils")]
#[deprecated(note = "Legacy migration shim; removed - use test fixtures with KeyManager")]
pub fn init_hmac_secret_for_test(_secret: impl Into<String>) -> Result<(), String> {
    Err(String::from(
        "init_hmac_secret_for_test is removed/deprecated: use test fixtures with KeyManager",
    ))
}
