#![allow(clippy::items_after_test_module)]
#![allow(clippy::collapsible_if)]
#![allow(unused_imports)]
use base64::Engine;

use crate::auth_context::TenantContext;
use crate::error::DataError;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use futures::future::BoxFuture;
use sea_orm::{
    ConnectionTrait, DatabaseConnection, DatabaseTransaction, DbBackend, DbErr, Statement,
    TransactionTrait,
};
use tracing::{error, warn};

// Sealed Internal Wrapper
pub struct RawConnection {
    pub(crate) txn: DatabaseTransaction,
}

impl RawConnection {
    pub(crate) fn new(txn: DatabaseTransaction) -> Self {
        Self { txn }
    }
}

/// A wrapper around a database transaction that is guaranteed to be scoped to a specific tenant.
pub struct TenantScoped<C> {
    pub(crate) inner: C,
    pub(crate) tenant_id: crate::auth_context::TenantId,
    pub(crate) user_id: Option<crate::auth_context::UserId>,
}

impl<C> TenantScoped<C> {
    pub(super) fn new(
        inner: C,
        tenant_id: crate::auth_context::TenantId,
        user_id: Option<crate::auth_context::UserId>,
    ) -> Self {
        Self {
            inner,
            tenant_id,
            user_id,
        }
    }
}

impl TenantScoped<RawConnection> {
    #[cfg(not(feature = "test-utils"))]
    pub(crate) fn txn(&self) -> &DatabaseTransaction {
        &self.inner.txn
    }

    /// # Safety
    ///
    /// This method exposes the raw database transaction, bypassing strict tenant scoping.
    /// Callers MUST ensure that any operations performed using this transaction
    /// are authorized via `flexi.authorize_tenant` or otherwise maintain tenant isolation invariants.
    ///
    /// This is exposed primarily for test seeding and special integration scenarios.
    #[cfg(feature = "test-utils")]
    pub(crate) fn txn(&self) -> &DatabaseTransaction {
        &self.inner.txn
    }

    pub(crate) async fn commit(self) -> Result<(), DbErr> {
        self.inner.txn.commit().await
    }

    pub(crate) async fn rollback(self) -> Result<(), DbErr> {
        self.inner.txn.rollback().await
    }
}

// Implement Sealed trait for TenantScoped
impl super::repository::private::Sealed for TenantScoped<RawConnection> {}

// TenantRepository implementation is in repository.rs

/// Executes a closure within a tenant-scoped transaction.
///
/// **Note:** This function relies on the `flexi.authorize_tenant` PL/pgSQL function.
/// The `token` must be a valid signed v2 token generated by `KeyManager`.
pub async fn with_tenant_tx<F, R>(
    pool: &DatabaseConnection,
    ctx: &TenantContext,
    token: &str,
    f: F,
) -> Result<R, DataError>
where
    F: for<'c> FnOnce(&'c TenantScoped<RawConnection>) -> BoxFuture<'c, Result<R, DataError>>
        + Send,
    R: Send,
{
    let txn = pool.begin().await.map_err(DataError::DbError)?;

    // 1. Authorize
    if let Err(e) = txn
        .execute(Statement::from_sql_and_values(
            DbBackend::Postgres,
            "SELECT flexi.authorize_tenant($1)",
            [token.into()],
        ))
        .await
    {
        // Log a sanitized message only; do not interpolate the raw DB error
        // to avoid leaking token KID or other sensitive fields into log sinks.
        warn!("Tenant authorization failed");

        let error_msg = e.to_string();
        let safe_error = [
            "Nonce already used",
            "Internal HMAC secret not set",
            "Invalid signature",
            "Token timestamp expired or future (skew > 30s)",
            "Missing or empty tenant token",
            "Invalid token format",
        ]
        .iter()
        .find(|&&m| error_msg.contains(m))
        .map(|&m| m.to_string())
        .unwrap_or_else(|| "tenant authorization failed".to_string());

        if let Err(rollback_err) = txn.rollback().await {
            error!("rollback failed after authorization failure: {rollback_err}");
        }
        return Err(DataError::TenantAuthorizationFailed(safe_error));
    }

    let token_tenant = if let Some(tid) = parse_tenant_from_token(token) {
        tid
    } else {
        if let Err(rollback_err) = txn.rollback().await {
            error!("rollback failed after token parse failure: {rollback_err}");
        }
        return Err(DataError::TenantAuthorizationFailed(
            "invalid tenant token format".to_string(),
        ));
    };
    if token_tenant != ctx.tenant_id().as_str() {
        warn!(
            expected_tenant = %ctx.tenant_id(),
            token_tenant = %token_tenant,
            "tenant mismatch between context and token"
        );
        if let Err(rollback_err) = txn.rollback().await {
            error!("rollback failed after tenant mismatch: {rollback_err}");
        }
        return Err(DataError::TenantAuthorizationFailed(
            "tenant mismatch between context and token".to_string(),
        ));
    }

    let scoped = TenantScoped::new(
        RawConnection::new(txn),
        ctx.tenant_id().clone(),
        ctx.user_id().cloned(),
    );

    match f(&scoped).await {
        Ok(result) => match scoped.commit().await {
            Ok(()) => Ok(result),
            Err(commit_err) => {
                error!(
                    tenant_id = %ctx.tenant_id(),
                    "commit failed (outcome unknown): {commit_err}"
                );
                Err(DataError::CommitUnknown(commit_err.to_string()))
            }
        },
        Err(e) => {
            if let Err(rollback_err) = scoped.rollback().await {
                error!("rollback failed: {rollback_err}");
            }
            warn!(tenant_id = %ctx.tenant_id(), "tx rolled back: {e}");
            Err(e)
        }
    }
}

fn parse_tenant_from_token(token: &str) -> Option<String> {
    #[cfg(feature = "test-utils")]
    if token.starts_with("v4.public.") {
        use base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD};
        let parts: Vec<&str> = token.split('.').collect();
        if parts.len() >= 3 {
            if let Ok(payload_bytes) = URL_SAFE_NO_PAD.decode(parts[2]) {
                // PASETO v4.public payload format is "message || 64-byte Ed25519 signature".
                // The parser must strip the last 64 bytes from the payload and then decode
                // the remaining bytes as JSON (the "message").
                if payload_bytes.len() > 64 {
                    let payload_len = payload_bytes.len() - 64;
                    let json_bytes = &payload_bytes[..payload_len];
                    if let Ok(s) = String::from_utf8(json_bytes.to_vec()) {
                        if let Ok(json) = serde_json::from_str::<serde_json::Value>(&s) {
                            if let Some(tid) = json.get("tenant_id").and_then(|v| v.as_str()) {
                                if !tid.is_empty() {
                                    return Some(tid.to_string());
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    #[cfg(any(test, feature = "test-utils"))]
    if let Some(tenant_id) = token.strip_prefix("dev-token:") {
        // Special dev token for tests/debug with tenant ID
        if !tenant_id.is_empty() {
            return Some(tenant_id.to_string());
        }
    }

    #[cfg(not(any(test, feature = "test-utils")))]
    if token.starts_with("dev-token:") {
        warn!("dev-token encountered in non-test build; parsing rejected");
        return None;
    }

    let mut parts = token.split(':');
    let ver = parts.next()?;
    let kid = parts.next()?;
    let ts = parts.next()?;
    let nonce = parts.next()?;
    let tenant_id = parts.next()?;
    let sig = parts.next()?;
    if ver != "v2"
        || parts.next().is_some()
        || kid.is_empty()
        || ts.is_empty()
        || nonce.is_empty()
        || tenant_id.is_empty()
        || sig.is_empty()
    {
        return None;
    }
    Some(tenant_id.to_string())
}

/// A tenant-scoped connection that additionally guarantees an authenticated user.
///
/// Unlike [`TenantScoped<RawConnection>`], this type holds a *concrete* [`UserId`] obtained
/// **after** the authentication middleware has already verified the token. It eliminates
/// the dual-source-of-truth problem where callers previously had to pass both a
/// `TenantScoped` handle (which carries `Option<UserId>`) and a separate `TenantContext`.
///
/// # Construction
///
/// Call [`AuthenticatedScoped::try_from_scoped`]. Construction succeeds only when
/// `scoped.user_id` is `Some`, which is guaranteed by the `ctx.user_id().is_none()`
/// fast-fail guard that runs in `load_permissions_middleware` before `with_tenant_tx`.
/// The `user_id` is always derived from the same `TenantScoped` handle — no external
/// `UserId` can be injected, preventing user-impersonation-by-misuse.
pub struct AuthenticatedScoped<'a> {
    scoped: &'a TenantScoped<RawConnection>,
    user_id: crate::auth_context::UserId,
}

impl<'a> AuthenticatedScoped<'a> {
    /// Construct an `AuthenticatedScoped` from a reference to an already-verified
    /// `TenantScoped` connection.
    ///
    /// Returns `Err` if `scoped.user_id` is `None` (unauthenticated context).  The
    /// `user_id` is always taken from `scoped` itself — callers cannot supply an
    /// arbitrary `UserId`, which prevents user-impersonation-by-misuse.
    ///
    /// The lifetime `'a` ties this struct to the lifetime of `scoped`, which is exactly
    /// what we need inside a `with_tenant_tx` closure where the transaction reference
    /// is borrowed for the duration of the closure.
    pub fn try_from_scoped(
        scoped: &'a TenantScoped<RawConnection>,
    ) -> Result<Self, crate::error::DataError> {
        let user_id = scoped
            .user_id
            .clone()
            .ok_or_else(|| {
                crate::error::DataError::ValidationError(
                    "AuthenticatedScoped requires a user_id in TenantScoped context".to_string(),
                )
            })?;
        Ok(Self { scoped, user_id })
    }

    pub fn tenant_id(&self) -> &crate::auth_context::TenantId {
        &self.scoped.tenant_id
    }

    pub fn user_id(&self) -> &crate::auth_context::UserId {
        &self.user_id
    }

    pub(crate) fn txn(&self) -> &DatabaseTransaction {
        self.scoped.txn()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_valid_token_returns_some() {
        let token = "v2:kid:ts:nonce:tenant-1:sig";
        assert_eq!(parse_tenant_from_token(token), Some("tenant-1".to_string()));
    }

    #[test]
    fn test_parse_missing_fields_returns_none() {
        assert_eq!(parse_tenant_from_token("v2:kid:ts:nonce:tenant-1"), None); // missing sig
        assert_eq!(parse_tenant_from_token("v2:kid:ts:nonce"), None); // missing tenant_id + sig
    }

    #[test]
    fn test_parse_extra_fields_returns_none() {
        assert_eq!(
            parse_tenant_from_token("v2:kid:ts:nonce:tenant-1:sig:extra"),
            None
        );
    }

    #[test]
    fn test_parse_wrong_version_returns_none() {
        assert_eq!(
            parse_tenant_from_token("v3:kid:ts:nonce:tenant-1:sig"),
            None
        );
    }

    #[test]
    fn test_parse_empty_tenant_returns_none() {
        let token = "v2:kid:ts:nonce::sig";
        assert_eq!(parse_tenant_from_token(token), None);
    }

    #[cfg(any(test, feature = "test-utils"))]
    mod test_utils_parsing {
        use super::*;
        use base64::engine::general_purpose::URL_SAFE_NO_PAD;

        #[test]
        fn test_dev_token_parsing() {
            // Valid
            assert_eq!(
                parse_tenant_from_token("dev-token:t1"),
                Some("t1".to_string())
            );

            // Empty tenant (should be rejected per hardening)
            assert_eq!(parse_tenant_from_token("dev-token:"), None);
        }

        #[cfg(feature = "test-utils")]
        #[test]
        fn test_v4_public_parsing() {
            let payload_json = r#"{"tenant_id":"t1","extra":"stuff"}"#;
            let payload_bytes = payload_json.as_bytes();
            let mut full_payload = payload_bytes.to_vec();
            full_payload.extend_from_slice(&[0u8; 64]); // Mock signature
            let b64 = URL_SAFE_NO_PAD.encode(&full_payload);
            let token = format!("v4.public.{}.footer", b64);

            assert_eq!(parse_tenant_from_token(&token), Some("t1".to_string()));
        }

        #[cfg(feature = "test-utils")]
        #[test]
        fn test_v4_public_empty_tenant_parsing() {
            let payload_json = r#"{"tenant_id":""}"#;
            let payload_bytes = payload_json.as_bytes();
            let mut full_payload = payload_bytes.to_vec();
            full_payload.extend_from_slice(&[0u8; 64]); // Mock signature
            let b64 = URL_SAFE_NO_PAD.encode(&full_payload);
            let token = format!("v4.public.{}.footer", b64);

            assert_eq!(parse_tenant_from_token(&token), None);
        }
    }

    #[cfg(not(feature = "test-utils"))]
    mod production_parsing {
        use super::*;

        #[test]
        fn test_dev_token_rejected() {
            assert_eq!(parse_tenant_from_token("dev-token:t1"), None);
        }

        #[test]
        fn test_v4_public_ignored() {
            // In prod, v4 public token parsing logic is compiled out or falls through
            // The function only parses v2 format if feature is disabled.
            // "v4.public..." does not match "v2:..." structure.
            let token = "v4.public.header.payload.footer";
            assert_eq!(parse_tenant_from_token(token), None);
        }
    }
}
