use crate::auth_context::TenantContext;
use crate::error::DataError;
use sea_orm::{
    ConnectionTrait, DatabaseConnection, DatabaseTransaction, DbBackend, DbErr, Statement,
    TransactionTrait,
};
use tracing::{error, warn};
use futures::future::BoxFuture;

// Sealed Internal Wrapper
pub struct RawConnection {
    pub(crate) txn: DatabaseTransaction,
}

impl RawConnection {
    pub(crate) fn new(txn: DatabaseTransaction) -> Self {
        Self { txn }
    }
}

/// A wrapper around a database transaction that is guaranteed to be scoped to a specific tenant.
pub struct TenantScoped<C> {
    pub(crate) inner: C,
    pub(crate) tenant_id: crate::auth_context::TenantId,
    pub(crate) user_id: Option<crate::auth_context::UserId>,
}

impl<C> TenantScoped<C> {
    pub(super) fn new(
        inner: C,
        tenant_id: crate::auth_context::TenantId,
        user_id: Option<crate::auth_context::UserId>,
    ) -> Self {
        Self {
            inner,
            tenant_id,
            user_id,
        }
    }
}

impl TenantScoped<RawConnection> {
    /// Access the underlying database transaction.
    ///
    /// # Visibility
    /// Restricted to `pub(crate)` to prevent external callers from bypassing
    /// tenant isolation. External crates (e.g., kernel-archiver) should use
    /// `TenantRepository` trait methods instead.
    #[allow(dead_code)]
    pub(crate) fn txn(&self) -> &DatabaseTransaction {
        &self.inner.txn
    }

    pub(crate) async fn commit(self) -> Result<(), DbErr> {
        self.inner.txn.commit().await
    }

    pub(crate) async fn rollback(self) -> Result<(), DbErr> {
        self.inner.txn.rollback().await
    }

}

// Implement Sealed trait for TenantScoped
impl super::repository::private::Sealed for TenantScoped<RawConnection> {}

// TenantRepository implementation is in repository.rs

/// Executes a closure within a tenant-scoped transaction.
///
/// **Note:** This function relies on the `flexi.authorize_tenant` PL/pgSQL function.
/// The `token` must be a valid signed v2 token generated by `KeyManager`.
pub async fn with_tenant_tx<F, R>(
    pool: &DatabaseConnection,
    ctx: &TenantContext,
    token: &str,
    f: F,
) -> Result<R, DataError>
where
    F: for<'c> FnOnce(&'c TenantScoped<RawConnection>) -> BoxFuture<'c, Result<R, DataError>> + Send,
    R: Send,
{
    let txn = pool.begin().await.map_err(DataError::DbError)?;

    // 1. Authorize
    txn.execute(Statement::from_sql_and_values(
        DbBackend::Postgres,
        "SELECT flexi.authorize_tenant($1)",
        [token.into()],
    ))
    .await
    .map_err(|e| {
        warn!("Tenant authorization failed via DB: {}", e);
        DataError::TenantAuthorizationFailed(e.to_string())
    })?;

    let scoped = TenantScoped::new(
        RawConnection::new(txn),
        ctx.tenant_id().clone(),
        ctx.user_id().cloned(),
    );

    match f(&scoped).await {
        Ok(result) => {
            match scoped.commit().await {
                Ok(()) => Ok(result),
                Err(commit_err) => {
                    error!(
                        tenant_id = %ctx.tenant_id(),
                        "commit failed (outcome unknown): {commit_err}"
                    );
                    Err(DataError::CommitUnknown(commit_err.to_string()))
                }
            }
        },
        Err(e) => {
            if let Err(rollback_err) = scoped.rollback().await {
                error!("rollback failed: {rollback_err}");
            }
            warn!(tenant_id = %ctx.tenant_id(), "tx rolled back: {e}");
            Err(e)
        }
    }
}

// Legacy exports for compatibility if needed (deprecated)
pub fn init_hmac_secret() -> Result<(), String> {
    // No-op or return error as it's no longer used
    Ok(())
}

#[cfg(feature = "test-utils")]
pub fn init_hmac_secret_for_test(_secret: impl Into<String>) -> Result<(), String> {
     // No-op
    Ok(())
}
