use axum::{
    body::Body,
    http::{Request, StatusCode},
};
use kernel_api::auth::{TenantContext, TenantId, UserId};
use kernel_api::entities::permission;
use kernel_api::middleware::{BearerToken, load_permissions_middleware, require_permission};
use sea_orm::{DatabaseBackend, MockDatabase};
use std::sync::Arc;
use tower::ServiceExt;
use uuid::Uuid;

// TODO: Implement a full integration test with Testcontainers (real Postgres)
// to verify the SQL join query generated by RBACRepository::get_user_permissions.
// The current tests only verify the middleware logic using MockDatabase.

#[tokio::test]
async fn test_rbac_middleware_allow() {
    let tenant_id = "tenant-1";
    let user_id = "user-1";
    let token = "v2:kid:ts:nonce:tenant-1:sig"; // Mock token format matching parser expectation

    let perm_id = Uuid::new_v4();
    let role_id = Uuid::new_v4();
    let now = chrono::Utc::now();

    // 1. First query: authorize_tenant (called by with_tenant_tx)
    // 2. Second query: RBACRepository::get_user_permissions
    // 3. Third query: commit (implicit in with_tenant_tx logic for successful runs?) - Actually with_tenant_tx does commit.

    // We mock the authorize_tenant call to succeed
    // Note: MockDatabase::append_exec_results is for execute, append_query_results is for select.
    // authorize_tenant is called via execute("SELECT flexi.authorize_tenant(...)")
    // MockDatabase handles execute by returning ExecResult, not QueryResult.

    let mock_permission = permission::Model {
        id: perm_id,
        tenant_id: tenant_id.to_string(),
        role_id: role_id,
        resource: "test".to_string(),
        action: "read".to_string(),
        created_at: now.into(),
        updated_at: now.into(),
    };

    let db = MockDatabase::new(DatabaseBackend::Postgres)
        .append_exec_results(vec![sea_orm::MockExecResult {
            last_insert_id: 0,
            rows_affected: 1,
        }]) // authorize_tenant (execute)
        .append_query_results(vec![vec![mock_permission]]) // permissions query (select)
        .into_connection();

    let app = axum::Router::new()
        .route(
            "/protected",
            axum::routing::get(|| async { "Allowed" }).layer(axum::middleware::from_fn(
                |req, next| require_permission("test:read", req, next),
            )),
        )
        .layer(axum::middleware::from_fn(load_permissions_middleware))
        .layer(axum::Extension(BearerToken(token.to_string())))
        .layer(axum::Extension(
            TenantContext::new(
                TenantId::new(tenant_id).unwrap(),
                Some(UserId::new(user_id).unwrap()),
            )
            .with_db(Arc::new(db)),
        ));

    let req = Request::builder()
        .uri("/protected")
        .header("Authorization", format!("Bearer {}", token))
        .body(Body::empty())
        .unwrap();

    let res = app.oneshot(req).await.unwrap();
    assert_eq!(res.status(), StatusCode::OK);
}

#[tokio::test]
async fn test_rbac_middleware_deny() {
    let tenant_id = "tenant-1";
    let user_id = "user-1";
    let token = "v2:kid:ts:nonce:tenant-1:sig";

    // User has other:write, but needs test:read
    let db = MockDatabase::new(DatabaseBackend::Postgres)
        .append_exec_results(vec![sea_orm::MockExecResult {
            last_insert_id: 0,
            rows_affected: 1,
        }]) // authorize_tenant (execute)
        .append_query_results(vec![vec![permission::Model {
            id: Uuid::new_v4(),
            tenant_id: tenant_id.to_string(),
            role_id: Uuid::new_v4(),
            resource: "other".to_string(),
            action: "write".to_string(),
            created_at: chrono::Utc::now().into(),
            updated_at: chrono::Utc::now().into(),
        }]])
        .into_connection();

    let app = axum::Router::new()
        .route(
            "/protected",
            axum::routing::get(|| async { "Allowed" }).layer(axum::middleware::from_fn(
                |req, next| require_permission("test:read", req, next),
            )),
        )
        .layer(axum::middleware::from_fn(load_permissions_middleware))
        .layer(axum::Extension(BearerToken(token.to_string())))
        .layer(axum::Extension(
            TenantContext::new(
                TenantId::new(tenant_id).unwrap(),
                Some(UserId::new(user_id).unwrap()),
            )
            .with_db(Arc::new(db)),
        ));

    let req = Request::builder()
        .uri("/protected")
        .header("Authorization", format!("Bearer {}", token))
        .body(Body::empty())
        .unwrap();

    let res = app.oneshot(req).await.unwrap();
    assert_eq!(res.status(), StatusCode::FORBIDDEN);
}
